[workspace]
members = [
    "backend",
    "backend_common",
    "backend_macros",
    "commands",
    "common",
    "crypto",
    "db",
    "frontend",
    "frontend_common",
    "frontend_macros",
    "macros",
]
resolver = "2"
