[package]
name = "commands"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
chrono = { version = "0.4", features = ["serde"] }
common = { path = "../common" }
macros = { path = "../macros" }
serde = { version = "1.0", features = ["derive"] }
